### ISSUE TITLE
Uploading all existing posts for Indexing

### ISSUE THREAD

**Issue by pankajpatel** [mlbrgl/ghost-algolia#10]
As far as I understood the mechanism correctly, new posts which will be published will get added to the index.

How to achieve the indexing of existing blog data with this integration?

Possible solutions could be
- upload the ghost exports file
- get the Ghost API key on Netlify app start and fetch all the index-able data (posts, tags)

**Comment by mlbrgl** [comment]
Sorry the late reply @pankajpatel! I haven't worked with Ghost in a while so I'm not in the best place to advise on a strategy at the moment. 

In case you haven't noticed, in the latest release at the time of writing (https://github.com/mlbrgl/ghost-algolia/tree/3.1.0), I had the [bulk indexing](https://github.com/mlbrgl/ghost-algolia/tree/3.1.0#bulk-indexing) scenario covered through patching Ghost core. It was more of hack around the Ghost's limitations at the time and came with obvious maintenance issues. There might be a better way to deal with this through the Netlify setup.
